In [1]:
import torch
from torch import nn

In [ ]:
#torch.optim.SGD()的参数形式是什么呢？

In [6]:
net = nn.Sequential(nn.Linear(2, 4))
w = nn.Linear(2, 4)

In [4]:
w, w.bias

(Linear(in_features=2, out_features=4, bias=True),
 Parameter containing:
 tensor([-0.3660,  0.1349,  0.6868,  0.4529], requires_grad=True))

In [11]:
net.parameters(), type(net.parameters())

(<generator object Module.parameters at 0x7f68369f8190>, generator)

In [35]:
list(net.parameters())[0]

Parameter containing:
tensor([[ 0.6371, -0.2908],
        [-0.2030,  0.2937],
        [-0.2327, -0.6143],
        [-0.0055,  0.6542]], requires_grad=True)

In [25]:
params = [{'params':net[0].weight, 'weight_decay':2},
 {'params':net[0].bias}]

In [30]:
params

[{'params': Parameter containing:
  tensor([[ 0.6371, -0.2908],
          [-0.2030,  0.2937],
          [-0.2327, -0.6143],
          [-0.0055,  0.6542]], requires_grad=True),
  'weight_decay': 2},
 {'params': Parameter containing:
  tensor([ 0.4624, -0.3887, -0.5123, -0.3518], requires_grad=True)}]

In [28]:
params[0]['params'], params[0]['weight_decay']

(Parameter containing:
 tensor([[ 0.6371, -0.2908],
         [-0.2030,  0.2937],
         [-0.2327, -0.6143],
         [-0.0055,  0.6542]], requires_grad=True),
 2)

In [29]:
params[1]['params']

Parameter containing:
tensor([ 0.4624, -0.3887, -0.5123, -0.3518], requires_grad=True)

In [36]:
list(params)[0]

{'params': Parameter containing:
 tensor([[ 0.6371, -0.2908],
         [-0.2030,  0.2937],
         [-0.2327, -0.6143],
         [-0.0055,  0.6542]], requires_grad=True),
 'weight_decay': 2}